# Generated by Django 4.2.11 on 2024-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingHistory',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Level', models.IntegerField()),
                ('Type', models.CharField(max_length=2)),
                ('VehicleNumber', models.CharField(max_length=30)),
                ('Lot', models.CharField(max_length=20)),
                ('In', models.TimeField()),
                ('Out', models.TimeField()),
                ('Fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Level', models.IntegerField()),
                ('TWA', models.IntegerField()),
                ('FWA', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Role', models.CharField(choices=[('admin', 'Admin'), ('public', 'Public')], default='public', max_length=10)),
            ],
        ),
    ]
